services:
  backend:
    build: ./BackEnd
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=urlshort;Username=urlshort;Password=alskjdfa@alskdjfAAAb12
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
      image: postgres:16
      environment:
        POSTGRES_DB: urlshort
        POSTGRES_USER: urlshort
        POSTGRES_PASSWORD: alskjdfa@alskdjfAAAb12
      volumes:
        - postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U urlshort"]
        interval: 5s
        timeout: 5s
        retries: 5


volumes:
  postgres-data:

networks:
  default:
    name: app-network
    driver: bridge
