name: Deploy to Home Server

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          # Write the SSH private key to id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # Set appropriate permissions for the private key
          chmod 600 ~/.ssh/id_rsa
          # Add the server's SSH key to known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Deploy via SSH
        run: |
          ssh tavani@$SERVER_IP "
            cd url-shortener-web-sem-3-ubt/ || exit
            git pull origin main
            docker-compose down
            docker-compose up -d
          "
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}